import { FlaskConical, Clock, ShieldCheck } from "lucide-react";
import { Center } from "./center-card";

export interface CenterDetail {
  slug?: string;
  subHeading?: string;
  operatingHoursText?: string;
  certificates?: string[];
  startingPrice?: number;
  aboutText?: string;
  facilities?: string[];
  services?: {
    name: string;
    provider: string;
    price: number;
    timing: string;
  }[];
  address?: string;
  distance?: string;
  reviewsList?: {
    author: string;
    date: string;
    rating: number;
    comment: string;
    isAnonymous?: boolean;
  }[];
}

export interface CenterItem extends Center, CenterDetail {
  isClinic: boolean;
  isLab: boolean;
  hasSameDayResults: boolean;
  isAnonymous: boolean;
  hasHomeCollection: boolean;
}

export const mockCenters: CenterItem[] = [
  // Bihar Centers (7 items for pagination testing)
  {
    id: "patna-diagnostics-boring-road",
    name: "Patna Diagnostics & Research Center",
    area: "BORING ROAD, PATNA",
    locationState: "bihar",
    rating: 4.7,
    reviews: 142,
    image: "/images/diagnostic-lab.png",
    photoCount: 8,
    description:
      "Fully digital diagnostic lab in Patna. Offers certified blood tests, STD screening, and fast anonymous reporting.",
    tags: ["NABL Accredited", "Bihar Top Rated"],
    categories: [
      "Blood Test ( Diagnostics )",
      "STDs & Skin (Both Doctors)",
      "STDs Clinics ( Venereologist )",
      "Skin Clinics ( Dermatologist )",
    ],
    stats: [
      { icon: FlaskConical, label: "45 TESTS" },
      { icon: Clock, label: "8AM–8PM" },
      { icon: ShieldCheck, label: "PRIVATE" },
    ],
    doctor: { name: "Dr. K. K. Sinha", avatar: "KS" },
    accentTagBg: "bg-rose-500",
    accentText: "text-rose-500",
    accentIconBg: "#fff1f2",
    accentIconColor: "#e11d48",
    accentAvatarBg: "#fff1f2",
    accentAvatarFg: "#e11d48",
    accentBtn: "#e11d48",
    accentBtnHover: "#be123c",
    accentDot: "bg-rose-400",
    accentShadow: "rgba(225,29,72,0.30)",
    isClinic: false,
    isLab: true,
    hasSameDayResults: true,
    isAnonymous: true,
    hasHomeCollection: true,
    slug: "patna-diagnostics-boring-road",
    subHeading: "Confidential STD & Sexual Health Testing • Boring Road",
    operatingHoursText: "Mon- Sat: 8 Am To 8 Pm, Sun: 8 Am To 4 Pm",
    certificates: ["Verified Center", "NABL Certified Lab"],
    startingPrice: 999,
    aboutText: "Patna Diagnostics & Research Center is the premier clinical lab in Boring Road, Patna. It is widely recognized for highly accurate blood tests, sexual health checkups, and fast digital report deliveries.\n\n### Specialized Clinical Testing\n- Same-day processing for all major STD panels.\n- Fully automated blood analysis under certified supervision.\n- Advanced testing machinery with high sensitivity standards.\n\n### Patient Confidentiality Measures\n- Anonymous booking using dynamic alphanumeric IDs.\n- Private waiting rooms with strict confidentiality policies.\n- 100% discrete home collection envelopes with unmarked packaging.",
    facilities: ["Blood Tests", "ECG", "STD Screening", "Confidential Consultation"],
    services: [
      { name: "Blood Tests and Health Checkup Packages (Free Home Collection)", provider: "Redcliffe Labs Patna", price: 2499, timing: "Home Collection: 7 AM to 3 PM" },
      { name: "MRI Scans, CT Scans, X-Rays, Blood Tests and health checkups", provider: "Patna Scans & Labs", price: 2499, timing: "8 AM to 8 PM" },
      { name: "Full Panel Sexually Transmitted Infection (STI) Profile", provider: "Patna Diagnostics & Research Center", price: 1999, timing: "Same Day Reporting" }
    ],
    address: "P 120, Boring Road, Near Crossing, Patna, Bihar 800001",
    distance: "~1.5 km from center",
  },
  {
    id: "nalanda-pathlabs-patna",
    name: "Nalanda Pathlabs & STD Center",
    area: "KANKARBAGH, PATNA",
    locationState: "bihar",
    rating: 4.5,
    reviews: 98,
    image: "/images/std-clinic.png",
    photoCount: 6,
    description:
      "Safe, private, and 100% confidential testing clinic specializing in STDs and sexual health diagnostics.",
    tags: ["ISO Certified", "Confidential"],
    categories: ["Blood Test ( Diagnostics )", "STDs & Skin (Both Doctors)", "STDs Clinics ( Venereologist )"],
    stats: [
      { icon: FlaskConical, label: "22 TESTS" },
      { icon: Clock, label: "7AM–7PM" },
      { icon: ShieldCheck, label: "ANONYMOUS" },
    ],
    doctor: { name: "Dr. R. Prasad", avatar: "RP" },
    accentTagBg: "bg-violet-600",
    accentText: "text-violet-600",
    accentIconBg: "#f5f3ff",
    accentIconColor: "#7c3aed",
    accentAvatarBg: "#f5f3ff",
    accentAvatarFg: "#7c3aed",
    accentBtn: "#7c3aed",
    accentBtnHover: "#6d28d9",
    accentDot: "bg-violet-400",
    accentShadow: "rgba(124,58,237,0.30)",
    isClinic: true,
    isLab: false,
    hasSameDayResults: true,
    isAnonymous: true,
    hasHomeCollection: false,
  },
  {
    id: "mithila-care-darbhanga",
    name: "Mithila Care Diagnostic Lab",
    area: "LALBAGH, DARBHANGA",
    locationState: "bihar",
    rating: 4.6,
    reviews: 64,
    image: "/images/testing-center.png",
    photoCount: 5,
    description:
      "Darbhanga's primary private laboratory offering home sample collection and anonymous testing support.",
    tags: ["Home Collection", "Trusted"],
    categories: ["Blood Test ( Diagnostics )", "Skin Clinics ( Dermatologist )"],
    stats: [
      { icon: FlaskConical, label: "15 TESTS" },
      { icon: Clock, label: "8AM–6PM" },
      { icon: ShieldCheck, label: "CERTIFIED" },
    ],
    doctor: { name: "Dr. M. K. Jha", avatar: "MJ" },
    accentTagBg: "bg-emerald-600",
    accentText: "text-emerald-600",
    accentIconBg: "#ecfdf5",
    accentIconColor: "#059669",
    accentAvatarBg: "#ecfdf5",
    accentAvatarFg: "#059669",
    accentBtn: "#059669",
    accentBtnHover: "#047857",
    accentDot: "bg-emerald-400",
    accentShadow: "rgba(5,150,105,0.30)",
    isClinic: false,
    isLab: true,
    hasSameDayResults: false,
    isAnonymous: true,
    hasHomeCollection: true,
  },
  {
    id: "bihar-health-muzaffarpur",
    name: "Bihar Health & Diagnostics",
    area: "CAMPUS ROAD, MUZAFFARPUR",
    locationState: "bihar",
    rating: 4.4,
    reviews: 51,
    image: "/images/home-testing.png",
    photoCount: 4,
    description:
      "Reliable clinical pathology and diagnostics in Muzaffarpur, prioritizing patient privacy and safety.",
    tags: ["NABL Member", "Rapid Reports"],
    categories: ["Blood Test ( Diagnostics )"],
    stats: [
      { icon: FlaskConical, label: "18 TESTS" },
      { icon: Clock, label: "9AM–8PM" },
      { icon: ShieldCheck, label: "VERIFIED" },
    ],
    doctor: { name: "Dr. A. Verma", avatar: "AV" },
    accentTagBg: "bg-amber-500",
    accentText: "text-amber-600",
    accentIconBg: "#fffbeb",
    accentIconColor: "#d97706",
    accentAvatarBg: "#fffbeb",
    accentAvatarFg: "#d97706",
    accentBtn: "#d97706",
    accentBtnHover: "#b45309",
    accentDot: "bg-amber-400",
    accentShadow: "rgba(217,119,6,0.30)",
    isClinic: false,
    isLab: true,
    hasSameDayResults: false,
    isAnonymous: true,
    hasHomeCollection: false,
  },
  {
    id: "gaya-testing-center",
    name: "Gaya Pathological Lab",
    area: "STATION ROAD, GAYA",
    locationState: "bihar",
    rating: 4.5,
    reviews: 73,
    image: "/images/diagnostic-lab.png",
    photoCount: 6,
    description:
      "Premium diagnostic testing and blood sample processing in Gaya, with digital updates and private rooms.",
    tags: ["Accredited", "Top Rated"],
    categories: ["Blood Test ( Diagnostics )", "Skin Clinics ( Dermatologist )"],
    stats: [
      { icon: FlaskConical, label: "26 TESTS" },
      { icon: Clock, label: "8AM–8PM" },
      { icon: ShieldCheck, label: "PRIVATE" },
    ],
    doctor: { name: "Dr. P. Sen", avatar: "PS" },
    accentTagBg: "bg-sky-600",
    accentText: "text-sky-600",
    accentIconBg: "#f0f9ff",
    accentIconColor: "#0284c7",
    accentAvatarBg: "#f0f9ff",
    accentAvatarFg: "#0284c7",
    accentBtn: "#0284c7",
    accentBtnHover: "#0369a1",
    accentDot: "bg-sky-400",
    accentShadow: "rgba(2,132,199,0.30)",
    isClinic: false,
    isLab: true,
    hasSameDayResults: true,
    isAnonymous: true,
    hasHomeCollection: true,
  },
  {
    id: "bhagalpur-std-clinic",
    name: "Bhagalpur Sexual Health Clinic",
    area: "KOTWALI, BHAGALPUR",
    locationState: "bihar",
    rating: 4.8,
    reviews: 82,
    image: "/images/std-clinic.png",
    photoCount: 7,
    description:
      "Dedicated clinic for STD consultation and skin ailments in Bhagalpur. Experienced specialists and counsellors.",
    tags: ["Confidential", "Specialist"],
    categories: ["Blood Test ( Diagnostics )", "STDs & Skin (Both Doctors)", "STDs Clinics ( Venereologist )"],
    stats: [
      { icon: FlaskConical, label: "20 TESTS" },
      { icon: Clock, label: "9AM–7PM" },
      { icon: ShieldCheck, label: "ANONYMOUS" },
    ],
    doctor: { name: "Dr. J. K. Roy", avatar: "JR" },
    accentTagBg: "bg-rose-500",
    accentText: "text-rose-500",
    accentIconBg: "#fff1f2",
    accentIconColor: "#e11d48",
    accentAvatarBg: "#fff1f2",
    accentAvatarFg: "#e11d48",
    accentBtn: "#e11d48",
    accentBtnHover: "#be123c",
    accentDot: "bg-rose-400",
    accentShadow: "rgba(225,29,72,0.30)",
    isClinic: true,
    isLab: false,
    hasSameDayResults: true,
    isAnonymous: true,
    hasHomeCollection: false,
  },
  {
    id: "patna-skin-hair-clinic",
    name: "Patna Skin Care & STD Center",
    area: "EXHIBITION ROAD, PATNA",
    locationState: "bihar",
    rating: 4.6,
    reviews: 110,
    image: "/images/private-doctor.png",
    photoCount: 9,
    description:
      "Modern skin and venereology center providing full-panel STD checks, consultations and treatments.",
    tags: ["Specialist", "Premium Care"],
    categories: [
      "Blood Test ( Diagnostics )",
      "STDs & Skin (Both Doctors)",
      "STDs Clinics ( Venereologist )",
      "Skin Clinics ( Dermatologist )",
    ],
    stats: [
      { icon: FlaskConical, label: "32 TESTS" },
      { icon: Clock, label: "10AM–8PM" },
      { icon: ShieldCheck, label: "VERIFIED" },
    ],
    doctor: { name: "Dr. Anjali Verma", avatar: "AV" },
    accentTagBg: "bg-violet-600",
    accentText: "text-violet-600",
    accentIconBg: "#f5f3ff",
    accentIconColor: "#7c3aed",
    accentAvatarBg: "#f5f3ff",
    accentAvatarFg: "#7c3aed",
    accentBtn: "#7c3aed",
    accentBtnHover: "#6d28d9",
    accentDot: "bg-violet-400",
    accentShadow: "rgba(124,58,237,0.30)",
    isClinic: true,
    isLab: false,
    hasSameDayResults: false,
    isAnonymous: true,
    hasHomeCollection: true,
  },

  // Other India Locations (11 items)
  {
    id: "jmd-diagnostics-kolkata",
    name: "JMD Diagnostics Pvt Ltd",
    area: "PARK STREET, KOLKATA",
    locationState: "west bengal",
    rating: 4.8,
    reviews: 324,
    image: "/images/center-jmd.png",
    photoCount: 8,
    description:
      "Trusted STD testing in Kolkata, offering fully confidential & accurate results with same-day reports.",
    tags: ["NABL Accredited", "Top Rated"],
    categories: ["Blood Test ( Diagnostics )", "STDs & Skin (Both Doctors)"],
    stats: [
      { icon: FlaskConical, label: "24 TESTS" },
      { icon: Clock, label: "8AM–8PM" },
      { icon: ShieldCheck, label: "PRIVATE" },
    ],
    doctor: { name: "Dr. A. Mehta", avatar: "AM" },
    accentTagBg: "bg-rose-500",
    accentText: "text-rose-500",
    accentIconBg: "#fff1f2",
    accentIconColor: "#e11d48",
    accentAvatarBg: "#fff1f2",
    accentAvatarFg: "#e11d48",
    accentBtn: "#e11d48",
    accentBtnHover: "#be123c",
    accentDot: "bg-rose-400",
    accentShadow: "rgba(225,29,72,0.30)",
    isClinic: false,
    isLab: true,
    hasSameDayResults: true,
    isAnonymous: true,
    hasHomeCollection: false,
    slug: "jmd-diagnostics-kolkata",
    subHeading: "Confidential STD & Sexual Health Testing • West Bengal",
    operatingHoursText: "Mon- Sat: 8 Am To 8 Pm ,Sun : 8 Am To 4 Pm",
    certificates: ["Verified Center", "NABL Certified Lab"],
    startingPrice: 999,
    aboutText: "JMD Diagnostics Pvt Ltd is located in Kolkata. JMD Diagnostic Centre has a good reputation in Kolkata. This lab has the facility for Mri scans, CT scans, Ultrasound, Blood Tests & ECG.\n\nJMD Phoolbagan lab has the latest and most modern technology of machines. All modes of payment are accepted here. You can search your tests along with the prices online. It has received 3.2 ratings from Google users and 4.0 ratings from Justdial users.\n\nYou can get all information related to timing, location, address, map, and test prices on this page. All tests are to be done under the supervision of a skilled & qualified technician. You can get up to a 50% discount. You can also book your tests online here.",
    facilities: ["Mri scans", "CT scans", "Ultrasound", "Blood Tests", "ECG"],
    services: [
      { name: "Blood Tests and Health Checkup Packages (Free Home Collection)", provider: "Redcliffe Labs Kolkata", price: 2499, timing: "Home Collection: 7 AM to 3 PM" },
      { name: "MRI Scans, CT Scans, X-Rays, Blood Tests and Health Checkups", provider: "Aarthi Scans Bhowanipore [Kolkata]", price: 2499, timing: "24 Hours. Ultrasound Time May Vary." },
      { name: "Blood Tests and Health Checkup Packages (Free Home Collection)", provider: "Redcliffe Labs Kolkata", price: 2499, timing: "Home Collection: 7 AM to 3 PM" },
      { name: "MRI scans, CT scans, ECG, Echo, Blood tests and health checkups", provider: "Aarthi Scans & Labs- Netaji Nagar, Kolkata", price: 2499, timing: "Mon to Sun: 06:30am–10:00pm" },
      { name: "Blood Tests and Health Checkup Packages (Free Home Collection)", provider: "Redcliffe Labs Kolkata", price: 2499, timing: "Home Collection: 7 AM to 3 PM" }
    ],
    address: "P 336, CIT Rd, Phool Bagan, Kankurgachi, Kolkata, West Bengal 700054",
    distance: "~3.2 km from city center",
    reviewsList: [
      {
        author: "Anonymous Patient",
        date: "January 15, 2026",
        rating: 5,
        comment: "Very professional, discreet, and fast. Got results the same evening. Staff made me feel comfortable — highly recommend for anyone anxious about testing."
      }
    ]
  },
  {
    id: "vijaya-diagnostic-nallagandla",
    name: "Vijaya Diagnostic Centre",
    area: "NALLAGANDLA, HYDERABAD",
    locationState: "telangana",
    rating: 4.6,
    reviews: 312,
    image: "/images/center-vijaya.png",
    photoCount: 12,
    description:
      "Renowned diagnostic chain in South India, comprehensive STD panel testing with full privacy.",
    tags: ["ISO Certified", "Most Trusted"],
    categories: ["Blood Test ( Diagnostics )", "STDs Clinics ( Venereologist )"],
    stats: [
      { icon: FlaskConical, label: "30 TESTS" },
      { icon: Clock, label: "7AM–9PM" },
      { icon: ShieldCheck, label: "ANONYMOUS" },
    ],
    doctor: { name: "Dr. S. Rao", avatar: "SR" },
    accentTagBg: "bg-violet-600",
    accentText: "text-violet-600",
    accentIconBg: "#f5f3ff",
    accentIconColor: "#7c3aed",
    accentAvatarBg: "#f5f3ff",
    accentAvatarFg: "#7c3aed",
    accentBtn: "#7c3aed",
    accentBtnHover: "#6d28d9",
    accentDot: "bg-violet-400",
    accentShadow: "rgba(124,58,237,0.30)",
    isClinic: false,
    isLab: true,
    hasSameDayResults: true,
    isAnonymous: true,
    hasHomeCollection: false,
    slug: "vijaya-diagnostic-nallagandla",
    subHeading: "Premium Diagnostic Solutions & Sexual Wellness Diagnostics • Hyderabad",
    operatingHoursText: "Mon-Sat: 7 AM to 9 PM, Sun: 7 AM to 2 PM",
    certificates: ["CAP Certified Lab", "NABL Accredited"],
    startingPrice: 1199,
    aboutText: "Vijaya Diagnostic Centre in Nallagandla, Hyderabad is a premium branch of South India's largest diagnostic network. It offers high-precision diagnostics, blood panels, and completely confidential STD testing supervised by leading clinical pathologists.\n\n### Why Patients Trust Vijaya Nallagandla\n- India's leading fully automated laboratory workflow.\n- Coded patient registrations to preserve complete privacy.\n- CAP & NABL accredited reporting with absolute accuracy.\n- Clean, modern, and friendly facility with private screening sections.",
    facilities: ["Automated Clinical Pathlab", "Blood Testing", "Confidential Consultations", "Cardiology Checks", "Pathology Profiles"],
    services: [
      { name: "Blood Tests and Health Checkup Packages (Free Home Collection)", provider: "Redcliffe Labs Hyderabad", price: 2499, timing: "Home Collection: 7 AM to 3 PM" },
      { name: "Full Panel Sexually Transmitted Infection (STI) Profile", provider: "Vijaya Diagnostic Centre", price: 1999, timing: "Same Day Reporting" }
    ],
    address: "Plot No. 14, HUDA Layout, Nallagandla, Gachibowli, Hyderabad, Telangana 500019",
    distance: "~2.4 km from city center",
  },
  {
    id: "metro-diagnostics-chandigarh",
    name: "Metro Diagnostics Centre",
    area: "SECTOR 17, CHANDIGARH",
    locationState: "punjab",
    rating: 4.5,
    reviews: 87,
    image: "/images/center-metro.png",
    photoCount: 6,
    description:
      "Premium STD & sexual health testing with state-of-the-art equipment, complete confidentiality.",
    tags: ["Home Collection", "New"],
    categories: ["Blood Test ( Diagnostics )", "Skin Clinics ( Dermatologist )"],
    stats: [
      { icon: FlaskConical, label: "18 TESTS" },
      { icon: Clock, label: "7AM–7PM" },
      { icon: ShieldCheck, label: "CERTIFIED" },
    ],
    doctor: { name: "Dr. P. Singh", avatar: "PS" },
    accentTagBg: "bg-emerald-600",
    accentText: "text-emerald-600",
    accentIconBg: "#ecfdf5",
    accentIconColor: "#059669",
    accentAvatarBg: "#ecfdf5",
    accentAvatarFg: "#059669",
    accentBtn: "#059669",
    accentBtnHover: "#047857",
    accentDot: "bg-emerald-400",
    accentShadow: "rgba(5,150,105,0.30)",
    isClinic: false,
    isLab: true,
    hasSameDayResults: false,
    isAnonymous: true,
    hasHomeCollection: true,
    slug: "metro-diagnostics-chandigarh",
    subHeading: "Accredited Clinical Pathology & Sexual Health Profile Testing • Sector 17",
    operatingHoursText: "Mon-Sat: 7 AM to 7 PM, Sun: 8 AM to 2 PM",
    certificates: ["ISO 9001 Certified", "Verified Center"],
    startingPrice: 899,
    aboutText: "Metro Diagnostics Centre in Sector 17, Chandigarh is a premium laboratory offering a wide range of pathological tests and secure STD screening checkups. It is equipped with advanced clinical machinery to deliver reliable reports in Punjab and Chandigarh region.\n\n### Specialty Health Screenings\n- Rapid-result sexual health profile checkups.\n- Coded laboratory registration for maximum privacy.\n- Home sample collection in unmarked envelopes by professional technicians.\n- Online report retrieval with secure 256-bit encryption.",
    facilities: ["Clinical Lab", "Blood Tests", "Home Collection", "Discreet Screening", "Pathology Specialist"],
    services: [
      { name: "Blood Tests and Health Checkup Packages (Free Home Collection)", provider: "Metro Diagnostics Chandigarh", price: 2499, timing: "Home Collection: 7 AM to 3 PM" },
      { name: "Full Panel Sexually Transmitted Infection (STI) Profile", provider: "Metro Diagnostics Chandigarh", price: 1999, timing: "Same Day Reporting" }
    ],
    address: "SCO 142-143, Sector 17-C, Chandigarh, Punjab 160017",
    distance: "~1.2 km from city center",
  },
  {
    id: "apollo-diagnostics-delhi",
    name: "Apollo Diagnostics",
    area: "CONNAUGHT PLACE, DELHI",
    locationState: "delhi",
    rating: 4.8,
    reviews: 521,
    image: "/images/center-apollo.png",
    photoCount: 15,
    description:
      "Nationally renowned chain, widest range of STD & sexual health tests, certified accuracy.",
    tags: ["Pan-India", "Premium"],
    categories: [
      "Blood Test ( Diagnostics )",
      "STDs & Skin (Both Doctors)",
      "STDs Clinics ( Venereologist )",
      "Skin Clinics ( Dermatologist )",
    ],
    stats: [
      { icon: FlaskConical, label: "40 TESTS" },
      { icon: Clock, label: "6AM–10PM" },
      { icon: ShieldCheck, label: "VERIFIED" },
    ],
    doctor: { name: "Dr. R. Kapoor", avatar: "RK" },
    accentTagBg: "bg-amber-500",
    accentText: "text-amber-600",
    accentIconBg: "#fffbeb",
    accentIconColor: "#d97706",
    accentAvatarBg: "#fffbeb",
    accentAvatarFg: "#d97706",
    accentBtn: "#d97706",
    accentBtnHover: "#b45309",
    accentDot: "bg-amber-400",
    accentShadow: "rgba(217,119,6,0.30)",
    isClinic: false,
    isLab: true,
    hasSameDayResults: true,
    isAnonymous: true,
    hasHomeCollection: true,
    slug: "apollo-diagnostics-delhi",
    subHeading: "Premium Full-Panel STD Screening & Clinical Pathology • Connaught Place",
    operatingHoursText: "Mon-Sat: 6 AM to 10 PM, Sun: 7 AM to 5 PM",
    certificates: ["CAP Accredited", "NABL Certified", "ISO 15189"],
    startingPrice: 1499,
    aboutText: "Apollo Diagnostics is a leading clinical laboratory in Connaught Place, New Delhi. Backed by Apollo Health & Lifestyle, it is known for high-accuracy blood tests, anonymous STD screening, and quick turnaround times.\n\n### Why Choose Apollo Connaught Place?\n- Advanced diagnostic machinery for same-day clinical reports.\n- 100% confidential checkups with anonymous reporting.\n- CAP & NABL accredited laboratory processes.\n- Qualified pathologists supervising every profile check.\n\n### Patient Guidelines\n- No prior doctor prescription is required for walk-in STD screening.\n- Home sample collection is completely private, sent in unmarked sealed envelopes.\n- Patients receive digital access to download reports online.",
    facilities: ["NABL Certified Lab", "Blood Tests", "Home Collection", "Specialist Consultation", "Confidential Screenings"],
    services: [
      { name: "Blood Tests and Health Checkup Packages (Free Home Collection)", provider: "Apollo Diagnostics Delhi", price: 2499, timing: "Home Collection: 7 AM to 3 PM" },
      { name: "Full Panel Sexually Transmitted Infection (STI) Profile", provider: "Apollo Diagnostics Delhi", price: 1999, timing: "Same Day Reporting" }
    ],
    address: "H-4, Connaught Circus, Block H, Connaught Place, New Delhi, Delhi 110001",
    distance: "~0.5 km from metro station",
  },
  {
    id: "std-clinic-mumbai",
    name: "ConfidentialCare STD Clinic",
    area: "ANDHERI WEST, MUMBAI",
    locationState: "maharashtra",
    rating: 4.7,
    reviews: 203,
    image: "/images/center-std.png",
    photoCount: 9,
    description:
      "Specialist STD clinic — anonymous testing, expert counselling & rapid result delivery.",
    tags: ["Anonymous", "Specialist"],
    categories: ["Blood Test ( Diagnostics )", "STDs & Skin (Both Doctors)", "STDs Clinics ( Venereologist )"],
    stats: [
      { icon: FlaskConical, label: "22 TESTS" },
      { icon: Clock, label: "9AM–8PM" },
      { icon: ShieldCheck, label: "PRIVATE" },
    ],
    doctor: { name: "Dr. N. Shah", avatar: "NS" },
    accentTagBg: "bg-sky-600",
    accentText: "text-sky-600",
    accentIconBg: "#f0f9ff",
    accentIconColor: "#0284c7",
    accentAvatarBg: "#f0f9ff",
    accentAvatarFg: "#0284c7",
    accentBtn: "#0284c7",
    accentBtnHover: "#0369a1",
    accentDot: "bg-sky-400",
    accentShadow: "rgba(2,132,199,0.30)",
    isClinic: true,
    isLab: false,
    hasSameDayResults: true,
    isAnonymous: true,
    hasHomeCollection: false,
    slug: "std-clinic-mumbai",
    subHeading: "Specialized Sexual Health Consultation & Anonymous STD Panels • Andheri West",
    operatingHoursText: "Mon-Sat: 9 AM to 8 PM, Sun: Closed",
    certificates: ["Certified Venereologist", "100% Confidential Guarantee"],
    startingPrice: 1299,
    aboutText: "ConfidentialCare STD Clinic in Andheri West, Mumbai is a state-of-the-art clinic specializing in sexual wellness, venereology consultations, and rapid-delivery diagnostic tests. Led by Dr. N. Shah, the clinic focuses on offering safe, respectful, and fully anonymous counseling and diagnostics.\n\n### Confidential Sexual Wellness Services\n- Expert consultations for all types of sexually transmitted infections (STIs).\n- Absolute patient anonymity with zero record leaks.\n- Coded diagnostics and testing to protect identity.\n- Counseling support for patients before and after screenings.",
    facilities: ["Specialist Doctor Consultations", "Confidential STI Profiles", "Pre-test Counseling", "Rapid Reporting Lab"],
    services: [
      { name: "Blood Tests and Health Checkup Packages (Free Home Collection)", provider: "Redcliffe Labs Mumbai", price: 2499, timing: "Home Collection: 7 AM to 3 PM" },
      { name: "Full Panel Sexually Transmitted Infection (STI) Profile", provider: "ConfidentialCare STD Clinic", price: 1999, timing: "Same Day Reporting" }
    ],
    address: "SCO 201, Andheri Link Road, Andheri West, Mumbai, Maharashtra 400053",
    distance: "~1.8 km from metro station",
  },
  {
    id: "healthfirst-bangalore",
    name: "HealthFirst Diagnostics",
    area: "INDIRANAGAR, BANGALORE",
    locationState: "karnataka",
    rating: 4.4,
    reviews: 164,
    image: "/images/center-jmd.png",
    photoCount: 7,
    description:
      "Bangalore's most accessible STD testing centre, same-day results, walk-ins always welcome.",
    tags: ["Walk-In", "Popular"],
    categories: ["Blood Test ( Diagnostics )", "Skin Clinics ( Dermatologist )"],
    stats: [
      { icon: FlaskConical, label: "20 TESTS" },
      { icon: Clock, label: "8AM–9PM" },
      { icon: ShieldCheck, label: "CERTIFIED" },
    ],
    doctor: { name: "Dr. K. Iyer", avatar: "KI" },
    accentTagBg: "bg-pink-600",
    accentText: "text-pink-600",
    accentIconBg: "#fdf2f8",
    accentIconColor: "#db2777",
    accentAvatarBg: "#fdf2f8",
    accentAvatarFg: "#db2777",
    accentBtn: "#db2777",
    accentBtnHover: "#be185d",
    accentDot: "bg-pink-400",
    accentShadow: "rgba(219,39,119,0.30)",
    isClinic: false,
    isLab: true,
    hasSameDayResults: true,
    isAnonymous: true,
    hasHomeCollection: true,
  },
  {
    id: "delhi-sexual-health",
    name: "Delhi Sexual Health Foundation",
    area: "DWARKA, DELHI",
    locationState: "delhi",
    rating: 4.7,
    reviews: 145,
    image: "/images/std-clinic.png",
    photoCount: 8,
    description:
      "Comprehensive sexual wellness, private consultations, and rapid-result STD screening.",
    tags: ["Premium", "Confidential"],
    categories: ["STDs & Skin (Both Doctors)", "STDs Clinics ( Venereologist )"],
    stats: [
      { icon: FlaskConical, label: "35 TESTS" },
      { icon: Clock, label: "9AM–9PM" },
      { icon: ShieldCheck, label: "CONFIDENTIAL" },
    ],
    doctor: { name: "Dr. S. K. Gupta", avatar: "SG" },
    accentTagBg: "bg-rose-500",
    accentText: "text-rose-500",
    accentIconBg: "#fff1f2",
    accentIconColor: "#e11d48",
    accentAvatarBg: "#fff1f2",
    accentAvatarFg: "#e11d48",
    accentBtn: "#e11d48",
    accentBtnHover: "#be123c",
    accentDot: "bg-rose-400",
    accentShadow: "rgba(225,29,72,0.30)",
    isClinic: true,
    isLab: false,
    hasSameDayResults: true,
    isAnonymous: true,
    hasHomeCollection: false,
  },
  {
    id: "mumbai-pathology-bandra",
    name: "Bandra Pathology Laboratory",
    area: "BANDRA WEST, MUMBAI",
    locationState: "maharashtra",
    rating: 4.6,
    reviews: 184,
    image: "/images/diagnostic-lab.png",
    photoCount: 10,
    description:
      "Advanced clinical tests and pathlab diagnostics in Bandra. High-standard testing and safety guidelines.",
    tags: ["Accredited", "ISO Certified"],
    categories: ["Blood Test ( Diagnostics )", "Skin Clinics ( Dermatologist )"],
    stats: [
      { icon: FlaskConical, label: "50 TESTS" },
      { icon: Clock, label: "7AM–8PM" },
      { icon: ShieldCheck, label: "VERIFIED" },
    ],
    doctor: { name: "Dr. Rita Patel", avatar: "RP" },
    accentTagBg: "bg-emerald-600",
    accentText: "text-emerald-600",
    accentIconBg: "#ecfdf5",
    accentIconColor: "#059669",
    accentAvatarBg: "#ecfdf5",
    accentAvatarFg: "#059669",
    accentBtn: "#059669",
    accentBtnHover: "#047857",
    accentDot: "bg-emerald-400",
    accentShadow: "rgba(5,150,105,0.30)",
    isClinic: false,
    isLab: true,
    hasSameDayResults: true,
    isAnonymous: true,
    hasHomeCollection: true,
  },
  {
    id: "bangalore-wellness-center",
    name: "Indiranagar Diagnostic & Wellness",
    area: "INDIRANAGAR, BANGALORE",
    locationState: "karnataka",
    rating: 4.5,
    reviews: 139,
    image: "/images/testing-center.png",
    photoCount: 6,
    description:
      "Comprehensive diagnostic care, specialty clinics, and walk-in blood collection with instant reports.",
    tags: ["Premium", "NABL accredited"],
    categories: ["Blood Test ( Diagnostics )", "STDs & Skin (Both Doctors)"],
    stats: [
      { icon: FlaskConical, label: "25 TESTS" },
      { icon: Clock, label: "8AM–8PM" },
      { icon: ShieldCheck, label: "PRIVATE" },
    ],
    doctor: { name: "Dr. V. Prasad", avatar: "VP" },
    accentTagBg: "bg-amber-500",
    accentText: "text-amber-600",
    accentIconBg: "#fffbeb",
    accentIconColor: "#d97706",
    accentAvatarBg: "#fffbeb",
    accentAvatarFg: "#d97706",
    accentBtn: "#d97706",
    accentBtnHover: "#b45309",
    accentDot: "bg-amber-400",
    accentShadow: "rgba(217,119,6,0.30)",
    isClinic: false,
    isLab: true,
    hasSameDayResults: true,
    isAnonymous: true,
    hasHomeCollection: true,
  },
  {
    id: "hyderabad-std-consultancy",
    name: "Hyderabad Skin & Venereal Clinic",
    area: "HITEC CITY, HYDERABAD",
    locationState: "telangana",
    rating: 4.8,
    reviews: 219,
    image: "/images/private-doctor.png",
    photoCount: 11,
    description:
      "Confidential screening and specialist care for all STDs and dermatological problems in Hyderabad.",
    tags: ["Top Rated", "Specialist"],
    categories: [
      "STDs & Skin (Both Doctors)",
      "STDs Clinics ( Venereologist )",
      "Skin Clinics ( Dermatologist )",
    ],
    stats: [
      { icon: FlaskConical, label: "35 TESTS" },
      { icon: Clock, label: "9AM–9PM" },
      { icon: ShieldCheck, label: "ANONYMOUS" },
    ],
    doctor: { name: "Dr. K. Madhav", avatar: "KM" },
    accentTagBg: "bg-violet-600",
    accentText: "text-violet-600",
    accentIconBg: "#f5f3ff",
    accentIconColor: "#7c3aed",
    accentAvatarBg: "#f5f3ff",
    accentAvatarFg: "#7c3aed",
    accentBtn: "#7c3aed",
    accentBtnHover: "#6d28d9",
    accentDot: "bg-violet-400",
    accentShadow: "rgba(124,58,237,0.30)",
    isClinic: true,
    isLab: false,
    hasSameDayResults: true,
    isAnonymous: true,
    hasHomeCollection: false,
  },
];

export const featuredCenters = [
  {
    id: "jmd-diagnostics-kolkata",
    name: "JMD Diagnostics Pvt Ltd",
    area: "PARK STREET, KOLKATA",
    rating: 4.6,
    reviews: 128,
    image: "/images/center-jmd.png",
    photoCount: 8,
    description:
      "Trusted STD testing in Kolkata, offering fully confidential & accurate results with same-day reports.",
    tags: ["NABL Accredited", "Top Rated"],
    stats: [
      { icon: FlaskConical, label: "24 TESTS" },
      { icon: Clock,        label: "8AM–8PM"  },
      { icon: ShieldCheck,  label: "PRIVATE"  },
    ],
    doctor: { name: "Dr. A. Mehta", avatar: "AM" },
    /* accent palette */
    accentTagBg:    "bg-rose-500",
    accentText:     "text-rose-500",
    accentIconBg:   "#fff1f2",           // rose-50
    accentIconColor:"#e11d48",           // rose-600
    accentAvatarBg: "#fff1f2",
    accentAvatarFg: "#e11d48",
    accentBtn:      "#e11d48",
    accentBtnHover: "#be123c",
    accentDot:      "bg-rose-400",
    accentShadow:   "rgba(225,29,72,0.30)",
  },
  {
    id: "vijaya-diagnostic-nallagandla",
    name: "Vijaya Diagnostic Centre",
    area: "NALLAGANDLA, HYDERABAD",
    rating: 4.6,
    reviews: 312,
    image: "/images/center-vijaya.png",
    photoCount: 12,
    description:
      "Renowned diagnostic chain in South India, comprehensive STD panel testing with full privacy.",
    tags: ["ISO Certified", "Most Trusted"],
    stats: [
      { icon: FlaskConical, label: "30 TESTS" },
      { icon: Clock,        label: "7AM–9PM"  },
      { icon: ShieldCheck,  label: "ANONYMOUS"},
    ],
    doctor: { name: "Dr. S. Rao", avatar: "SR" },
    accentTagBg:    "bg-violet-600",
    accentText:     "text-violet-600",
    accentIconBg:   "#f5f3ff",
    accentIconColor:"#7c3aed",
    accentAvatarBg: "#f5f3ff",
    accentAvatarFg: "#7c3aed",
    accentBtn:      "#7c3aed",
    accentBtnHover: "#6d28d9",
    accentDot:      "bg-violet-400",
    accentShadow:   "rgba(124,58,237,0.30)",
  },
  {
    id: "metro-diagnostics-chandigarh",
    name: "Metro Diagnostics Centre",
    area: "SECTOR 17, CHANDIGARH",
    rating: 4.5,
    reviews: 87,
    image: "/images/center-metro.png",
    photoCount: 6,
    description:
      "Premium STD & sexual health testing with state-of-the-art equipment, complete confidentiality.",
    tags: ["Home Collection", "New"],
    stats: [
      { icon: FlaskConical, label: "18 TESTS" },
      { icon: Clock,        label: "7AM–7PM"  },
      { icon: ShieldCheck,  label: "CERTIFIED"},
    ],
    doctor: { name: "Dr. P. Singh", avatar: "PS" },
    accentTagBg:    "bg-emerald-600",
    accentText:     "text-emerald-600",
    accentIconBg:   "#ecfdf5",
    accentIconColor:"#059669",
    accentAvatarBg: "#ecfdf5",
    accentAvatarFg: "#059669",
    accentBtn:      "#059669",
    accentBtnHover: "#047857",
    accentDot:      "bg-emerald-400",
    accentShadow:   "rgba(5,150,105,0.30)",
  },
  {
    id: "apollo-diagnostics-delhi",
    name: "Apollo Diagnostics",
    area: "CONNAUGHT PLACE, DELHI",
    rating: 4.8,
    reviews: 521,
    image: "/images/center-apollo.png",
    photoCount: 15,
    description:
      "Nationally renowned chain, widest range of STD & sexual health tests, certified accuracy.",
    tags: ["Pan-India", "Premium"],
    stats: [
      { icon: FlaskConical, label: "40 TESTS" },
      { icon: Clock,        label: "6AM–10PM" },
      { icon: ShieldCheck,  label: "VERIFIED" },
    ],
    doctor: { name: "Dr. R. Kapoor", avatar: "RK" },
    accentTagBg:    "bg-amber-500",
    accentText:     "text-amber-600",
    accentIconBg:   "#fffbeb",
    accentIconColor:"#d97706",
    accentAvatarBg: "#fffbeb",
    accentAvatarFg: "#d97706",
    accentBtn:      "#d97706",
    accentBtnHover: "#b45309",
    accentDot:      "bg-amber-400",
    accentShadow:   "rgba(217,119,6,0.30)",
  },
  {
    id: "std-clinic-mumbai",
    name: "ConfidentialCare STD Clinic",
    area: "ANDHERI WEST, MUMBAI",
    rating: 4.7,
    reviews: 203,
    image: "/images/center-std.png",
    photoCount: 9,
    description:
      "Specialist STD clinic — anonymous testing, expert counselling & rapid result delivery.",
    tags: ["Anonymous", "Specialist"],
    stats: [
      { icon: FlaskConical, label: "22 TESTS" },
      { icon: Clock,        label: "9AM–8PM"  },
      { icon: ShieldCheck,  label: "PRIVATE"  },
    ],
    doctor: { name: "Dr. N. Shah", avatar: "NS" },
    accentTagBg:    "bg-sky-600",
    accentText:     "text-sky-600",
    accentIconBg:   "#f0f9ff",
    accentIconColor:"#0284c7",
    accentAvatarBg: "#f0f9ff",
    accentAvatarFg: "#0284c7",
    accentBtn:      "#0284c7",
    accentBtnHover: "#0369a1",
    accentDot:      "bg-sky-400",
    accentShadow:   "rgba(2,132,199,0.30)",
  },
  {
    id: "healthfirst-bangalore",
    name: "HealthFirst Diagnostics",
    area: "INDIRANAGAR, BANGALORE",
    rating: 4.4,
    reviews: 164,
    image: "/images/center-jmd.png",
    photoCount: 7,
    description:
      "Bangalore's most accessible STD testing centre, same-day results, walk-ins always welcome.",
    tags: ["Walk-In", "Popular"],
    stats: [
      { icon: FlaskConical, label: "20 TESTS" },
      { icon: Clock,        label: "8AM–9PM"  },
      { icon: ShieldCheck,  label: "CERTIFIED"},
    ],
    doctor: { name: "Dr. K. Iyer", avatar: "KI" },
    accentTagBg:    "bg-pink-600",
    accentText:     "text-pink-600",
    accentIconBg:   "#fdf2f8",
    accentIconColor:"#db2777",
    accentAvatarBg: "#fdf2f8",
    accentAvatarFg: "#db2777",
    accentBtn:      "#db2777",
    accentBtnHover: "#be185d",
    accentDot:      "bg-pink-400",
    accentShadow:   "rgba(219,39,119,0.30)",
  },
];

