import { FlaskConical, Clock, ShieldCheck } from "lucide-react";
import { Center } from "./center-card";

export const mockCenters: (Center & {
  isClinic: boolean;
  isLab: boolean;
  hasSameDayResults: boolean;
  isAnonymous: boolean;
  hasHomeCollection: boolean;
})[] = [
  // Bihar Centers (7 items for pagination testing)
  {
    id: "patna-diagnostics-boring-road",
    name: "Patna Diagnostics & Research Center",
    area: "BORING ROAD, PATNA",
    locationState: "bihar",
    rating: 4.7,
    reviews: 142,
    image: "/images/diagnostic-lab.png",
    photoCount: 8,
    description:
      "Fully digital diagnostic lab in Patna. Offers certified blood tests, STD screening, and fast anonymous reporting.",
    tags: ["NABL Accredited", "Bihar Top Rated"],
    categories: [
      "Blood Test ( Diagnostics )",
      "STDs & Skin (Both Doctors)",
      "STDs Clinics ( Venereologist )",
      "Skin Clinics ( Dermatologist )",
    ],
    stats: [
      { icon: FlaskConical, label: "45 TESTS" },
      { icon: Clock, label: "8AM–8PM" },
      { icon: ShieldCheck, label: "PRIVATE" },
    ],
    doctor: { name: "Dr. K. K. Sinha", avatar: "KS" },
    accentTagBg: "bg-rose-500",
    accentText: "text-rose-500",
    accentIconBg: "#fff1f2",
    accentIconColor: "#e11d48",
    accentAvatarBg: "#fff1f2",
    accentAvatarFg: "#e11d48",
    accentBtn: "#e11d48",
    accentBtnHover: "#be123c",
    accentDot: "bg-rose-400",
    accentShadow: "rgba(225,29,72,0.30)",
    isClinic: false,
    isLab: true,
    hasSameDayResults: true,
    isAnonymous: true,
    hasHomeCollection: true,
  },
  {
    id: "nalanda-pathlabs-patna",
    name: "Nalanda Pathlabs & STD Center",
    area: "KANKARBAGH, PATNA",
    locationState: "bihar",
    rating: 4.5,
    reviews: 98,
    image: "/images/std-clinic.png",
    photoCount: 6,
    description:
      "Safe, private, and 100% confidential testing clinic specializing in STDs and sexual health diagnostics.",
    tags: ["ISO Certified", "Confidential"],
    categories: ["STDs & Skin (Both Doctors)", "STDs Clinics ( Venereologist )"],
    stats: [
      { icon: FlaskConical, label: "22 TESTS" },
      { icon: Clock, label: "7AM–7PM" },
      { icon: ShieldCheck, label: "ANONYMOUS" },
    ],
    doctor: { name: "Dr. R. Prasad", avatar: "RP" },
    accentTagBg: "bg-violet-600",
    accentText: "text-violet-600",
    accentIconBg: "#f5f3ff",
    accentIconColor: "#7c3aed",
    accentAvatarBg: "#f5f3ff",
    accentAvatarFg: "#7c3aed",
    accentBtn: "#7c3aed",
    accentBtnHover: "#6d28d9",
    accentDot: "bg-violet-400",
    accentShadow: "rgba(124,58,237,0.30)",
    isClinic: true,
    isLab: false,
    hasSameDayResults: true,
    isAnonymous: true,
    hasHomeCollection: false,
  },
  {
    id: "mithila-care-darbhanga",
    name: "Mithila Care Diagnostic Lab",
    area: "LALBAGH, DARBHANGA",
    locationState: "bihar",
    rating: 4.6,
    reviews: 64,
    image: "/images/testing-center.png",
    photoCount: 5,
    description:
      "Darbhanga's primary private laboratory offering home sample collection and anonymous testing support.",
    tags: ["Home Collection", "Trusted"],
    categories: ["Blood Test ( Diagnostics )", "Skin Clinics ( Dermatologist )"],
    stats: [
      { icon: FlaskConical, label: "15 TESTS" },
      { icon: Clock, label: "8AM–6PM" },
      { icon: ShieldCheck, label: "CERTIFIED" },
    ],
    doctor: { name: "Dr. M. K. Jha", avatar: "MJ" },
    accentTagBg: "bg-emerald-600",
    accentText: "text-emerald-600",
    accentIconBg: "#ecfdf5",
    accentIconColor: "#059669",
    accentAvatarBg: "#ecfdf5",
    accentAvatarFg: "#059669",
    accentBtn: "#059669",
    accentBtnHover: "#047857",
    accentDot: "bg-emerald-400",
    accentShadow: "rgba(5,150,105,0.30)",
    isClinic: false,
    isLab: true,
    hasSameDayResults: false,
    isAnonymous: true,
    hasHomeCollection: true,
  },
  {
    id: "bihar-health-muzaffarpur",
    name: "Bihar Health & Diagnostics",
    area: "CAMPUS ROAD, MUZAFFARPUR",
    locationState: "bihar",
    rating: 4.4,
    reviews: 51,
    image: "/images/home-testing.png",
    photoCount: 4,
    description:
      "Reliable clinical pathology and diagnostics in Muzaffarpur, prioritizing patient privacy and safety.",
    tags: ["NABL Member", "Rapid Reports"],
    categories: ["Blood Test ( Diagnostics )"],
    stats: [
      { icon: FlaskConical, label: "18 TESTS" },
      { icon: Clock, label: "9AM–8PM" },
      { icon: ShieldCheck, label: "VERIFIED" },
    ],
    doctor: { name: "Dr. A. Verma", avatar: "AV" },
    accentTagBg: "bg-amber-500",
    accentText: "text-amber-600",
    accentIconBg: "#fffbeb",
    accentIconColor: "#d97706",
    accentAvatarBg: "#fffbeb",
    accentAvatarFg: "#d97706",
    accentBtn: "#d97706",
    accentBtnHover: "#b45309",
    accentDot: "bg-amber-400",
    accentShadow: "rgba(217,119,6,0.30)",
    isClinic: false,
    isLab: true,
    hasSameDayResults: false,
    isAnonymous: true,
    hasHomeCollection: false,
  },
  {
    id: "gaya-testing-center",
    name: "Gaya Pathological Lab",
    area: "STATION ROAD, GAYA",
    locationState: "bihar",
    rating: 4.5,
    reviews: 73,
    image: "/images/diagnostic-lab.png",
    photoCount: 6,
    description:
      "Premium diagnostic testing and blood sample processing in Gaya, with digital updates and private rooms.",
    tags: ["Accredited", "Top Rated"],
    categories: ["Blood Test ( Diagnostics )", "Skin Clinics ( Dermatologist )"],
    stats: [
      { icon: FlaskConical, label: "26 TESTS" },
      { icon: Clock, label: "8AM–8PM" },
      { icon: ShieldCheck, label: "PRIVATE" },
    ],
    doctor: { name: "Dr. P. Sen", avatar: "PS" },
    accentTagBg: "bg-sky-600",
    accentText: "text-sky-600",
    accentIconBg: "#f0f9ff",
    accentIconColor: "#0284c7",
    accentAvatarBg: "#f0f9ff",
    accentAvatarFg: "#0284c7",
    accentBtn: "#0284c7",
    accentBtnHover: "#0369a1",
    accentDot: "bg-sky-400",
    accentShadow: "rgba(2,132,199,0.30)",
    isClinic: false,
    isLab: true,
    hasSameDayResults: true,
    isAnonymous: true,
    hasHomeCollection: true,
  },
  {
    id: "bhagalpur-std-clinic",
    name: "Bhagalpur Sexual Health Clinic",
    area: "KOTWALI, BHAGALPUR",
    locationState: "bihar",
    rating: 4.8,
    reviews: 82,
    image: "/images/std-clinic.png",
    photoCount: 7,
    description:
      "Dedicated clinic for STD consultation and skin ailments in Bhagalpur. Experienced specialists and counsellors.",
    tags: ["Confidential", "Specialist"],
    categories: ["STDs & Skin (Both Doctors)", "STDs Clinics ( Venereologist )"],
    stats: [
      { icon: FlaskConical, label: "20 TESTS" },
      { icon: Clock, label: "9AM–7PM" },
      { icon: ShieldCheck, label: "ANONYMOUS" },
    ],
    doctor: { name: "Dr. J. K. Roy", avatar: "JR" },
    accentTagBg: "bg-rose-500",
    accentText: "text-rose-500",
    accentIconBg: "#fff1f2",
    accentIconColor: "#e11d48",
    accentAvatarBg: "#fff1f2",
    accentAvatarFg: "#e11d48",
    accentBtn: "#e11d48",
    accentBtnHover: "#be123c",
    accentDot: "bg-rose-400",
    accentShadow: "rgba(225,29,72,0.30)",
    isClinic: true,
    isLab: false,
    hasSameDayResults: true,
    isAnonymous: true,
    hasHomeCollection: false,
  },
  {
    id: "patna-skin-hair-clinic",
    name: "Patna Skin Care & STD Center",
    area: "EXHIBITION ROAD, PATNA",
    locationState: "bihar",
    rating: 4.6,
    reviews: 110,
    image: "/images/private-doctor.png",
    photoCount: 9,
    description:
      "Modern skin and venereology center providing full-panel STD checks, consultations and treatments.",
    tags: ["Specialist", "Premium Care"],
    categories: [
      "STDs & Skin (Both Doctors)",
      "STDs Clinics ( Venereologist )",
      "Skin Clinics ( Dermatologist )",
    ],
    stats: [
      { icon: FlaskConical, label: "32 TESTS" },
      { icon: Clock, label: "10AM–8PM" },
      { icon: ShieldCheck, label: "VERIFIED" },
    ],
    doctor: { name: "Dr. Anjali Verma", avatar: "AV" },
    accentTagBg: "bg-violet-600",
    accentText: "text-violet-600",
    accentIconBg: "#f5f3ff",
    accentIconColor: "#7c3aed",
    accentAvatarBg: "#f5f3ff",
    accentAvatarFg: "#7c3aed",
    accentBtn: "#7c3aed",
    accentBtnHover: "#6d28d9",
    accentDot: "bg-violet-400",
    accentShadow: "rgba(124,58,237,0.30)",
    isClinic: true,
    isLab: false,
    hasSameDayResults: false,
    isAnonymous: true,
    hasHomeCollection: true,
  },

  // Other India Locations (11 items)
  {
    id: "jmd-diagnostics-kolkata",
    name: "JMD Diagnostics Pvt Ltd",
    area: "PARK STREET, KOLKATA",
    locationState: "west bengal",
    rating: 4.6,
    reviews: 128,
    image: "/images/center-jmd.png",
    photoCount: 8,
    description:
      "Trusted STD testing in Kolkata, offering fully confidential & accurate results with same-day reports.",
    tags: ["NABL Accredited", "Top Rated"],
    categories: ["Blood Test ( Diagnostics )", "STDs & Skin (Both Doctors)"],
    stats: [
      { icon: FlaskConical, label: "24 TESTS" },
      { icon: Clock, label: "8AM–8PM" },
      { icon: ShieldCheck, label: "PRIVATE" },
    ],
    doctor: { name: "Dr. A. Mehta", avatar: "AM" },
    accentTagBg: "bg-rose-500",
    accentText: "text-rose-500",
    accentIconBg: "#fff1f2",
    accentIconColor: "#e11d48",
    accentAvatarBg: "#fff1f2",
    accentAvatarFg: "#e11d48",
    accentBtn: "#e11d48",
    accentBtnHover: "#be123c",
    accentDot: "bg-rose-400",
    accentShadow: "rgba(225,29,72,0.30)",
    isClinic: false,
    isLab: true,
    hasSameDayResults: true,
    isAnonymous: true,
    hasHomeCollection: false,
  },
  {
    id: "vijaya-diagnostic-nallagandla",
    name: "Vijaya Diagnostic Centre",
    area: "NALLAGANDLA, HYDERABAD",
    locationState: "telangana",
    rating: 4.6,
    reviews: 312,
    image: "/images/center-vijaya.png",
    photoCount: 12,
    description:
      "Renowned diagnostic chain in South India, comprehensive STD panel testing with full privacy.",
    tags: ["ISO Certified", "Most Trusted"],
    categories: ["Blood Test ( Diagnostics )", "STDs Clinics ( Venereologist )"],
    stats: [
      { icon: FlaskConical, label: "30 TESTS" },
      { icon: Clock, label: "7AM–9PM" },
      { icon: ShieldCheck, label: "ANONYMOUS" },
    ],
    doctor: { name: "Dr. S. Rao", avatar: "SR" },
    accentTagBg: "bg-violet-600",
    accentText: "text-violet-600",
    accentIconBg: "#f5f3ff",
    accentIconColor: "#7c3aed",
    accentAvatarBg: "#f5f3ff",
    accentAvatarFg: "#7c3aed",
    accentBtn: "#7c3aed",
    accentBtnHover: "#6d28d9",
    accentDot: "bg-violet-400",
    accentShadow: "rgba(124,58,237,0.30)",
    isClinic: false,
    isLab: true,
    hasSameDayResults: true,
    isAnonymous: true,
    hasHomeCollection: false,
  },
  {
    id: "metro-diagnostics-chandigarh",
    name: "Metro Diagnostics Centre",
    area: "SECTOR 17, CHANDIGARH",
    locationState: "punjab",
    rating: 4.5,
    reviews: 87,
    image: "/images/center-metro.png",
    photoCount: 6,
    description:
      "Premium STD & sexual health testing with state-of-the-art equipment, complete confidentiality.",
    tags: ["Home Collection", "New"],
    categories: ["Blood Test ( Diagnostics )", "Skin Clinics ( Dermatologist )"],
    stats: [
      { icon: FlaskConical, label: "18 TESTS" },
      { icon: Clock, label: "7AM–7PM" },
      { icon: ShieldCheck, label: "CERTIFIED" },
    ],
    doctor: { name: "Dr. P. Singh", avatar: "PS" },
    accentTagBg: "bg-emerald-600",
    accentText: "text-emerald-600",
    accentIconBg: "#ecfdf5",
    accentIconColor: "#059669",
    accentAvatarBg: "#ecfdf5",
    accentAvatarFg: "#059669",
    accentBtn: "#059669",
    accentBtnHover: "#047857",
    accentDot: "bg-emerald-400",
    accentShadow: "rgba(5,150,105,0.30)",
    isClinic: false,
    isLab: true,
    hasSameDayResults: false,
    isAnonymous: true,
    hasHomeCollection: true,
  },
  {
    id: "apollo-diagnostics-delhi",
    name: "Apollo Diagnostics",
    area: "CONNAUGHT PLACE, DELHI",
    locationState: "delhi",
    rating: 4.8,
    reviews: 521,
    image: "/images/center-apollo.png",
    photoCount: 15,
    description:
      "Nationally renowned chain, widest range of STD & sexual health tests, certified accuracy.",
    tags: ["Pan-India", "Premium"],
    categories: [
      "Blood Test ( Diagnostics )",
      "STDs & Skin (Both Doctors)",
      "STDs Clinics ( Venereologist )",
      "Skin Clinics ( Dermatologist )",
    ],
    stats: [
      { icon: FlaskConical, label: "40 TESTS" },
      { icon: Clock, label: "6AM–10PM" },
      { icon: ShieldCheck, label: "VERIFIED" },
    ],
    doctor: { name: "Dr. R. Kapoor", avatar: "RK" },
    accentTagBg: "bg-amber-500",
    accentText: "text-amber-600",
    accentIconBg: "#fffbeb",
    accentIconColor: "#d97706",
    accentAvatarBg: "#fffbeb",
    accentAvatarFg: "#d97706",
    accentBtn: "#d97706",
    accentBtnHover: "#b45309",
    accentDot: "bg-amber-400",
    accentShadow: "rgba(217,119,6,0.30)",
    isClinic: false,
    isLab: true,
    hasSameDayResults: true,
    isAnonymous: true,
    hasHomeCollection: true,
  },
  {
    id: "std-clinic-mumbai",
    name: "ConfidentialCare STD Clinic",
    area: "ANDHERI WEST, MUMBAI",
    locationState: "maharashtra",
    rating: 4.7,
    reviews: 203,
    image: "/images/center-std.png",
    photoCount: 9,
    description:
      "Specialist STD clinic — anonymous testing, expert counselling & rapid result delivery.",
    tags: ["Anonymous", "Specialist"],
    categories: ["STDs & Skin (Both Doctors)", "STDs Clinics ( Venereologist )"],
    stats: [
      { icon: FlaskConical, label: "22 TESTS" },
      { icon: Clock, label: "9AM–8PM" },
      { icon: ShieldCheck, label: "PRIVATE" },
    ],
    doctor: { name: "Dr. N. Shah", avatar: "NS" },
    accentTagBg: "bg-sky-600",
    accentText: "text-sky-600",
    accentIconBg: "#f0f9ff",
    accentIconColor: "#0284c7",
    accentAvatarBg: "#f0f9ff",
    accentAvatarFg: "#0284c7",
    accentBtn: "#0284c7",
    accentBtnHover: "#0369a1",
    accentDot: "bg-sky-400",
    accentShadow: "rgba(2,132,199,0.30)",
    isClinic: true,
    isLab: false,
    hasSameDayResults: true,
    isAnonymous: true,
    hasHomeCollection: false,
  },
  {
    id: "healthfirst-bangalore",
    name: "HealthFirst Diagnostics",
    area: "INDIRANAGAR, BANGALORE",
    locationState: "karnataka",
    rating: 4.4,
    reviews: 164,
    image: "/images/center-jmd.png",
    photoCount: 7,
    description:
      "Bangalore's most accessible STD testing centre, same-day results, walk-ins always welcome.",
    tags: ["Walk-In", "Popular"],
    categories: ["Blood Test ( Diagnostics )", "Skin Clinics ( Dermatologist )"],
    stats: [
      { icon: FlaskConical, label: "20 TESTS" },
      { icon: Clock, label: "8AM–9PM" },
      { icon: ShieldCheck, label: "CERTIFIED" },
    ],
    doctor: { name: "Dr. K. Iyer", avatar: "KI" },
    accentTagBg: "bg-pink-600",
    accentText: "text-pink-600",
    accentIconBg: "#fdf2f8",
    accentIconColor: "#db2777",
    accentAvatarBg: "#fdf2f8",
    accentAvatarFg: "#db2777",
    accentBtn: "#db2777",
    accentBtnHover: "#be185d",
    accentDot: "bg-pink-400",
    accentShadow: "rgba(219,39,119,0.30)",
    isClinic: false,
    isLab: true,
    hasSameDayResults: true,
    isAnonymous: true,
    hasHomeCollection: true,
  },
  {
    id: "delhi-sexual-health",
    name: "Delhi Sexual Health Foundation",
    area: "DWARKA, DELHI",
    locationState: "delhi",
    rating: 4.7,
    reviews: 145,
    image: "/images/std-clinic.png",
    photoCount: 8,
    description:
      "Comprehensive sexual wellness, private consultations, and rapid-result STD screening.",
    tags: ["Premium", "Confidential"],
    categories: ["STDs & Skin (Both Doctors)", "STDs Clinics ( Venereologist )"],
    stats: [
      { icon: FlaskConical, label: "35 TESTS" },
      { icon: Clock, label: "9AM–9PM" },
      { icon: ShieldCheck, label: "CONFIDENTIAL" },
    ],
    doctor: { name: "Dr. S. K. Gupta", avatar: "SG" },
    accentTagBg: "bg-rose-500",
    accentText: "text-rose-500",
    accentIconBg: "#fff1f2",
    accentIconColor: "#e11d48",
    accentAvatarBg: "#fff1f2",
    accentAvatarFg: "#e11d48",
    accentBtn: "#e11d48",
    accentBtnHover: "#be123c",
    accentDot: "bg-rose-400",
    accentShadow: "rgba(225,29,72,0.30)",
    isClinic: true,
    isLab: false,
    hasSameDayResults: true,
    isAnonymous: true,
    hasHomeCollection: false,
  },
  {
    id: "mumbai-pathology-bandra",
    name: "Bandra Pathology Laboratory",
    area: "BANDRA WEST, MUMBAI",
    locationState: "maharashtra",
    rating: 4.6,
    reviews: 184,
    image: "/images/diagnostic-lab.png",
    photoCount: 10,
    description:
      "Advanced clinical tests and pathlab diagnostics in Bandra. High-standard testing and safety guidelines.",
    tags: ["Accredited", "ISO Certified"],
    categories: ["Blood Test ( Diagnostics )", "Skin Clinics ( Dermatologist )"],
    stats: [
      { icon: FlaskConical, label: "50 TESTS" },
      { icon: Clock, label: "7AM–8PM" },
      { icon: ShieldCheck, label: "VERIFIED" },
    ],
    doctor: { name: "Dr. Rita Patel", avatar: "RP" },
    accentTagBg: "bg-emerald-600",
    accentText: "text-emerald-600",
    accentIconBg: "#ecfdf5",
    accentIconColor: "#059669",
    accentAvatarBg: "#ecfdf5",
    accentAvatarFg: "#059669",
    accentBtn: "#059669",
    accentBtnHover: "#047857",
    accentDot: "bg-emerald-400",
    accentShadow: "rgba(5,150,105,0.30)",
    isClinic: false,
    isLab: true,
    hasSameDayResults: true,
    isAnonymous: true,
    hasHomeCollection: true,
  },
  {
    id: "bangalore-wellness-center",
    name: "Indiranagar Diagnostic & Wellness",
    area: "INDIRANAGAR, BANGALORE",
    locationState: "karnataka",
    rating: 4.5,
    reviews: 139,
    image: "/images/testing-center.png",
    photoCount: 6,
    description:
      "Comprehensive diagnostic care, specialty clinics, and walk-in blood collection with instant reports.",
    tags: ["Premium", "NABL accredited"],
    categories: ["Blood Test ( Diagnostics )", "STDs & Skin (Both Doctors)"],
    stats: [
      { icon: FlaskConical, label: "25 TESTS" },
      { icon: Clock, label: "8AM–8PM" },
      { icon: ShieldCheck, label: "PRIVATE" },
    ],
    doctor: { name: "Dr. V. Prasad", avatar: "VP" },
    accentTagBg: "bg-amber-500",
    accentText: "text-amber-600",
    accentIconBg: "#fffbeb",
    accentIconColor: "#d97706",
    accentAvatarBg: "#fffbeb",
    accentAvatarFg: "#d97706",
    accentBtn: "#d97706",
    accentBtnHover: "#b45309",
    accentDot: "bg-amber-400",
    accentShadow: "rgba(217,119,6,0.30)",
    isClinic: false,
    isLab: true,
    hasSameDayResults: true,
    isAnonymous: true,
    hasHomeCollection: true,
  },
  {
    id: "hyderabad-std-consultancy",
    name: "Hyderabad Skin & Venereal Clinic",
    area: "HITEC CITY, HYDERABAD",
    locationState: "telangana",
    rating: 4.8,
    reviews: 219,
    image: "/images/private-doctor.png",
    photoCount: 11,
    description:
      "Confidential screening and specialist care for all STDs and dermatological problems in Hyderabad.",
    tags: ["Top Rated", "Specialist"],
    categories: [
      "STDs & Skin (Both Doctors)",
      "STDs Clinics ( Venereologist )",
      "Skin Clinics ( Dermatologist )",
    ],
    stats: [
      { icon: FlaskConical, label: "35 TESTS" },
      { icon: Clock, label: "9AM–9PM" },
      { icon: ShieldCheck, label: "ANONYMOUS" },
    ],
    doctor: { name: "Dr. K. Madhav", avatar: "KM" },
    accentTagBg: "bg-violet-600",
    accentText: "text-violet-600",
    accentIconBg: "#f5f3ff",
    accentIconColor: "#7c3aed",
    accentAvatarBg: "#f5f3ff",
    accentAvatarFg: "#7c3aed",
    accentBtn: "#7c3aed",
    accentBtnHover: "#6d28d9",
    accentDot: "bg-violet-400",
    accentShadow: "rgba(124,58,237,0.30)",
    isClinic: true,
    isLab: false,
    hasSameDayResults: true,
    isAnonymous: true,
    hasHomeCollection: false,
  },
];
